### PR TITLE
Port mongodsb codebase

### PR DESCRIPTION
**Pull request by shpandrak**

### CODE REVIEW

**Comment by rpellows** [comment]
@shpandrak Getting WARNINGs using buildimage.sh
Since you know maven better than most of us, can you address this malformed project issue.

---
```
[WARNING] Some problems were encountered while building the effective model for com.emc.ocopea.mongodsb:k8s-mongodsb:pom:0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 38, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```

**Comment by shpandrak** [comment]
@rpellows I have fixed the maven warnings. I have added another commit for that which I can squash before merging

**Comment by mrmccarthy** [comment]
When trying to run the tests, I tripped over:
```
$ go test
# ocopea/k8s-mongodsb/restapi/operations/dsb_web
../operations/dsb_web/copy_service_instance.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/create_service_instance.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/delete_service_instance.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/get_d_s_b_icon.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/get_d_s_b_info.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/get_service_instance.go:43: assignment count mismatch: 3 = 2
../operations/dsb_web/get_service_instances.go:43: assignment count mismatch: 3 = 2
FAIL	ocopea/k8s-mongodsb/restapi/impl [build failed]

```
I've got 0.11.0 of swagger.

Working with Amar, I then cleaned up the pkgs and directories created in src from github.com etc. and did a godep restore.  This generated:

```
$ ~/cndp/bin/godep restore
# cd /home/mmccarth/cndp/src/golang.org/x/text; git checkout bsf4b4367115ec2de254587813edaa901bc1c723a8
error: pathspec 'bsf4b4367115ec2de254587813edaa901bc1c723a8' did not match any file(s) known to git.
godep: error downloading dep (golang.org/x/text/secure/bidirule): exit status 1
godep: error downloading dep (ocopea/kubernetes/client): unrecognized import path "ocopea/kubernetes/client"
godep: error downloading dep (ocopea/kubernetes/client/inf): unrecognized import path "ocopea/kubernetes/client/inf"
godep: error downloading dep (ocopea/kubernetes/client/resource): unrecognized import path "ocopea/kubernetes/client/resource"
godep: error downloading dep (ocopea/kubernetes/client/types): unrecognized import path "ocopea/kubernetes/client/types"
godep: error downloading dep (ocopea/kubernetes/client/unversioned): unrecognized import path "ocopea/kubernetes/client/unversioned"
godep: error downloading dep (ocopea/kubernetes/client/v1): unrecognized import path "ocopea/kubernetes/client/v1"
godep: Error downloading some deps. Aborting restore and check.

```
I assume this is the same issue Rob mentioned with the SHA that's no longer   ##available.

**Update**
My VM has swagger 0.11.0.  I jumped on another VM which had swagger 0.9.0, and it avoided the arg mismatch and was able to complete the swagger command and go test without error **once** I had created my repo under GOPATH/src/ocopea/k8s-mongodsb.   

I had cloned the repo under GOPATH/src/k8s-mongodsb and there were errors with the test import finding the models.  

Do we have standard text for GO projects and the proper path/git clone requirements?  It should be noted here.

**Comment by rpellows** [comment]
File `./restapi/configure_k8s_mongodsb.go`
has
` 42     nazNS := os.Getenv("NAZ_NAMESPACE")`

What is the purpose?  Can it be OCOPEA_NAMESPACE?

**Comment by shpandrak** [comment]
> Update
> My VM has swagger 0.11.0. I jumped on another VM which had swagger 0.9.0, and it avoided the arg mismatch and was able to complete the swagger command and go test without error once I had created my repo under GOPATH/src/ocopea/k8s-mongodsb.
> 
> I had cloned the repo under GOPATH/src/k8s-mongodsb and there were errors with the test import finding the models.
> 
> Do we have standard text for GO projects and the proper path/git clone requirements? It should be noted here.

Thanks @mrmccarthy . I'll update the readme to point at  GOPATH/src/ocopea/k8s-mongodsb as this is the correct directory
Besides that the docs say swagger 0.10.0 :) we can add instructions for running that in a container. not sure it is mandatory to going public though.

**Comment by shpandrak** [comment]
> File ./restapi/configure_k8s_mongodsb.go
> has
> 42 nazNS := os.Getenv("NAZ_NAMESPACE")
> 
> What is the purpose? Can it be OCOPEA_NAMESPACE?

Fix committed. notice that the change required a fix in the kubernetes repo as well so make sure you rebuild k8spsb and get latest deployer if you want to test the deployment...

**Comment by shpandrak** [comment]
@mrmccarthy I have fixed the instructions explaining where to clone on the GOPATH

**Comment by shpandrak** [comment]
I have also committed changes to README.md according to the comments made yesterday on the KT. see details in commit message

**Review by vjtirumalai — COMMENTED** [review]
@shpandrak I have added few cleanup commits. You may want to rebase it once you review.

I am still figuring out why I cannot restore the dependency from godeps.

**Comment by shpandrak** [comment]
> @shpandrak I have added few cleanup commits. You may want to rebase it once you review.
> 
> I am still figuring out why I cannot restore the dependency from godeps.

@vjtirumalai thanks for the cleaups, I am good with keeping your commits as is and merge.
Regarding the Godeps. I agreed with Rob to defer that for after going public. I did fix what he required to do...

**Review by vjtirumalai — APPROVED** [review]
Made sense to me to squash the commits.  Nothing interesting in there. Merging now. More changes in future PRs.

**Pull request merged**
